config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}


  get '/404', :to => "errors#not_found"
  get '/422', :to => "errors#unacceptable"
  get '/500', :to => "errors#server_error"  

  get '/about', :to => "pages#about"


  resources :properties

  get '/select_property' => "properties#select"
  
  # Authenticated route to show Dashboard as root when used signed
  authenticated :user do 
  	root to: 'pages#dashboard', as: "authenticated_user" 
  end

  root to: 'pages#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user	
  validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	def not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found', layout:'layouts/application',status: 404}	
      format.all { render nothing: true, status: 404}
	  end
	end

	def server_error
    respond_to do |format|
      format.html { render template: 'errors/server_error', layout: 'layouts/error', status: 500 }
      format.all  { render nothing: true, status: 500}
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render template: 'errors/unacceptable', layout: 'layouts/error', status: 422 }
      format.all  { render nothing: true, status: 422}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def dashboard
  	#If we have some properties setup
  	if any_properties? 
  	  #	But no properties currently selected
      if !property_selected?
      	#Get the user to select one
  		redirect_to properties_path 
  	  #If a property was selected but no rooms	
  	  else
  	  	dashboard_home 
  	  end
  	else
  		first_time_home
  	end

  end

  protected 
    def dashboard_home 
    	render 'dashboard'
    end

    def first_time_home
    	render 'first_time'
    end


end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :assign_property, only: [:show, :edit, :update, :destroy]	
  before_action :access_restriction, only:[:show, :edit, :update, :destroy]

  def index
  	@properties = current_user.properties
  end

  def show
  end

  def new
    @property = current_user.properties.new
  end

  def create
  	@property = current_user.properties.new(property_params)
  	if @property.save
  	  flash[:success] = I18n.t :property_saved_success
  	  redirect_to properties_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	@property.assign_attributes(property_params)
  	if @property.save 
  	  flash[:success] = I18n.t :property_updated_success
      redirect_to properties_path
  	else
  	  render :edit
    end
  end

  def destroy
  	#If we destroy the currently selected property
  	#we need to reset it
  	is_current = is_current_property?(@property)
  	if @property.destroy
  		flash[:success] = I18n.t :property_deleted_success
  		clear_current_property if is_current
  		redirect_to properties_path
  	else
  		flash[:danger] = I18n.t :property_deleted_failure
  	end
  end

  def select
    property = Property.find(params[:id])
    set_current_property(property)
    redirect_to root_path
  end

  private
    def property_params
      params.require(:property)
      .permit(:description, :address, :address2,
      	      :city, :state, :zip)
    end

    def assign_property
      @property = Property.find(params[:id])
    end

    def access_restriction
      redirect_to(root_path, flash: {danger: (I18n.t :unauthorized_access_resource)}) unless(@property.user == current_user)	
    end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  def create
    super

   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?
    msg =""
    resource.errors.full_messages.each do |m| 
      #message.each do |m| 
        msg = msg + content_tag(:li, m)
      #end
    end 
    sentence = I18n.t("devise.errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class = "card border-danger mb-3">
      <div class = "card-header text-danger">
       <strong>#{sentence}</strong>
      </div>
      <div class = "card-body text-danger">
          <ul>#{msg}</ul>
      </div>
    </div>  
    HTML

    html.html_safe
  end
end

app/helpers/display_helper.rb
module DisplayHelper
  def link_with_icon(link, action, id, description, confirm="", turbo=true)	
    case action 
    when "show"
      a_tag = <<-HTML
      <a href="#{link}" id="#{id}" >
      <i class="far fa-file-alt fa-2x trunfo-main" 
      aria-hidden="true" 
      data-html = "true" 
      data-toggle="tooltip" 
      title="#{description}" 
      data-placement="right">
      </i>
      </a>
      HTML
    when "edit"
      a_tag = <<-HTML
      <a data-turbolinks="#{turbo}" 
      href="#{link}" id="#{id}">
      <i class="fas fa-edit fa-2x trunfo-main" 
      aria-hidden="true" 
      data-html = "true" 
      data-toggle="tooltip" 
      title="#{description}" 
      data-placement="right">
      </i>
      </a>
      HTML

    when "delete" 
      a_tag = <<-HTML
      <a data-confirm="#{confirm}" rel="nofollow" data-method="delete" 
      href="#{link}" id="#{id}">
      <i class="far fa-trash-alt fa-2x trunfo-main" 
      aria-hidden="true" 
      data-html = "true" 
      data-toggle="tooltip" 
      title="#{description}" 
      data-placement="right">
      </i>
      </a>
      HTML

    when "manage"  
      a_tag = <<-HTML
      <a data-turbolinks="#{turbo}" 
      href="#{link}" id="#{id}" >
      <i class="far fa-folder fa-2x trunfo-main" 
      aria-hidden="true" 
      data-html = "true" 
      data-toggle="tooltip" 
      title="#{description}" 
      data-placement="right">
      </i>
      </a>
      HTML

    end 
    a_tag.html_safe
  end

end           

app/helpers/sessions_helper.rb
module SessionsHelper  
  
  def set_current_property(property)
    session[:property_id] = property.id 
  end	
  
  def is_current_property?(property)
  	property == current_property 
  end	

  def clear_current_property
  	current_property = nil
  end

  def current_property
  	current_property ||= Property.find(session[:property_id]) if session[:property_id]
  rescue ActiveRecord::RecordNotFound
  	current_property = nil 
  end

  def property_selected?
  	!current_property.nil?
  end

  def any_properties?
  	current_user.properties.count > 0
  end

  def property_count
  	current_user.properties.count
  end

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trunfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="shortcut icon" 
      type="image/x-icon" 
      href = <%=asset_pack_path "media/images/favicon.ico"%>>
  </head>

  <body data-controller="<%= controller_name %> <%= action_name %>">
    <nav class = "navbar navbar-expand-md mb-4" role="navigation">
      <div class = "container-fluid">
        <!-- Home Button with Logo -->
        <%= link_to root_path, class: "navbar-brand" do %>
          <%=image_pack_tag("trunfo_transparent.png", alt:"Trunfo Large", class: "d-none d-lg-block  aign-middle") %>
          <%=image_pack_tag("trunfo_logo.png", alt:"Trunfo Small", class: "d-lg-none d-inline-block aign-middle") %>
        <%end%>
        <button  class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#main-nav-collapse" aria-controls= "main-nav-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <i class = "fas fa-bars trunfo-main"> </i>
          
           
        </button>
        <%=render "shared/menubar"%>
      </div>
    </nav>
    <div class = "container-fluid content">
      <div class = "row">
        <div class = "col-12">
          <%flash.each do |name,msg| %>
            <%unless name.to_s == 'timedout'%>
              <div class='alert alert-<%="#{name}" %>'>
                <a href ='#' class='close' data-dismiss='alert'>&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <%end%>
          <%end%>
          <%flash.discard()%>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trunfo</title>
  <%= csrf_meta_tags %>
  <style>
    body {
        background: #fff;
        font-family: Helvetica, Arial, Sans-Serif;
        font-size: 14px;
    }
    .error_container {
        display: block;
        margin: auto;
        margin: 10% auto 0 auto;
        width: 40%;
    }
    .error_container .error {
        display: block; 
        text-align: center;
    }
    .error_container .error img {
        display: block;
        margin: 0 auto 25px auto;
    }
    
  </style>
</head>
<body>
  <div class="error_container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class = "row">
  <div class = "col-12">
	  <h5 id ="about1" class = "trunfo-main">
      <%= t :about1_html%>
    </h5>
    <br>
    <h5 id ="about2" class = "trunfo-main">
      <%= t :about2_html%>
    </h5>
    <ul class = "trunfo-main">
    	<li><%= t :reason1_html%></li>
    	<li><%= t :reason2_html%></li>
    	<li><%= t :reason3_html%></li>
    	<li><%= t :reason4_html%></li>
    </ul>
    
    <h5 id ="about3" class = "trunfo-main text-justify">
      <%= t :about3_html%>
    </h5>
    <br>
    <h4 id ="about4" class = "trunfo-main text-justify">
        <%= t :about4_html%>
    </h4>
    <br>
	<h5 id ="about5" class = "trunfo-main text-justify">
      <%= t :about5_html%>
    </h5>
	<br>
	<h5 id ="about6" class = "trunfo-main text-justify">
      <%= t :about6_html%>
    </h5>
	<br>
	<h5 id ="about7" class = "trunfo-main text-justify">
      <%= t :about7_html%>
    </h5>
  </div>
</div>
  

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

app/views/pages/first_time.html.erb
<div class = "row">
  <div class = "col-12">
    <h2 class = "text-center trunfo-main">
      <%= t :no_properties_setup%>
  	</h2>
    <h2 class = "text-center trunfo-main">
      <%= t :click_to_create_property%>
    </h2>
  </div>
</div>
<br>
<div class = "row">
  <div class = "col-12 text-center">
    <%=link_to (t :add_property_button), new_property_path,
    data: {turbolinks: false},
    class: "btn btn-trunfo"%>
  </div>
</div>

app/views/pages/home.html.erb
<div class = "row">
  <div class = "col-12 col-md-6 col-lg-8">
    <div class = "col-12">
  	  <%=image_pack_tag("trunfo.jpg", 
                        style: 'width:100%',
                        id:"main-logo")%>
    </div>
    <div class = "row">
      <div class = "col-12 col-md-12 col-lg-8">
        <h5 class = "trunfo-main" 
            style="padding-left: 50px;display: inline-block">
          <%=I18n.t('trunfo_mottos').sample%>
        </h5>
      </div>
      <div class = "col-12 col-md-12 col-lg-4" style="text-align:right">
        <%= link_to (t :find_out_more), about_path,
            class:"btn btn-trunfo"%>
      </div>
    </div>
    <br>
  </div>

  <div class = "col-12 col-md-6 col-lg-4">
  	<div class = "card">
  		<div class = "card-header login_header">
  			<h5><%= t :welcome%></h5>
  		</div>
  	  <div class = "card-body">	
        <%=form_for(:user, :url => session_path(:user)) do |f| %>
          <div class = "form-group">
            <%=f.email_field :email, class: "form-control",
            placeholder: "Email"%>
          </div>
          <div class = "form-group">
            <%=f.password_field :password, class: "form-control",
            placeholder: "Password" %>
          </div>
    
          <div class = "form-check">
            <%= f.check_box :remember_me,
            class: "form-check-input" %>
            <%= f.label :remember_me,(t :remember),
            class: "form-check-label" %>
          </div>
          <br>
          <%= f.submit 'Log In',
          class: "btn btn-block btn-trunfo" %>
          <br>
          <%=link_to (t :forgot_pass),
            new_password_path(:user) %>
          <br>
          <%=link_to (t :sign_up),
            new_user_registration_path, id: 'registration_link' %>
        <% end %> 
      </div>   
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
  <div class = "form-row col-12">
    <!-- Description -->
    <div class = "form-group form-row col-12">
      <%= f.label :description,
      class: "col-12 col-lg-2 
              col-form-label col-form-label-sm label-bold"%>
      <div class = "col-12 col-lg-10">
        <%= f.text_field :description, autofocus: true,
        class: "form-control form-control-sm col"%>
      </div>
    </div>
    
    <!-- Address -->  	      
    <div class = "form-group form-row col-12">
   	  <%= f.label :address,
          class: "col-12 col-lg-2 
                  col-form-label col-form-label-sm label-bold"%>
   	  <div class = "col-12 col-lg-10">
   	    <%= f.text_field :address, 
        class: "form-control form-control-sm col"%>
   	  </div>
    </div>
  
    <!-- Address2 -->	      
    <div class = "form-group form-row col-12">
      <div class = "col-12 col-lg-2 
                    col-form-label col-form-label-sm label-bold">
  	  </div>
  	  <div class = "col-12 col-lg-10">
  	    <%= f.text_field :address2, 
        class: "form-control form-control-sm col"%>
  	  </div>
    </div>
    
    <!-- City -->	      
    <div class = "form-group form-row col-12">
   	  <%=f.label :city,  
      class: "col-12 col-lg-2 
              col-form-label col-form-label-sm label-bold"%>
   	  <div class = "col-12 col-lg-10">
   	    <%= f.text_field :city, 
        class: "form-control form-control-sm col"%>
      </div>
    </div>
    <div class = "form-group form-row col-12">
    <!-- State & Zip -->
    
      <!-- State -->
   	  <%=f.label :state,  
        class: "col-12 col-lg-2 
                col-form-label col-form-label-sm label-bold"%>
  	  <div class = "col-3 col-md-2 col-lg-1">
   	    <%= f.text_field :state,
        class: "form-control form-control-sm col"%>
      </div>
   </div>
   
   <div class = "form-group form-row col-12">
      <!-- Zip -->
      <%=f.label :zip, "Zip", 
       class: "col-12 col-lg-2 
              col-form-label col-form-label-sm label-bold"%>
      <div class = "col-5 col-md-3 col-lg-2">
        <%=f.text_field :zip,
        class: "form-control form-control-sm col"%>
      </div>
    </div>
  </div>

app/views/properties/_no_properties.html.erb
<div class = "row">
  <div class = "col-12">
  	<!-- No Properties Message -->
    <h2 class = "text-center trunfo-main">
      <%= t :property_list_no_properties%>
    </h2>
  </div>
</div>

app/views/properties/_property_list.html.erb
<div class = "row">
  <div class = "col-12">
    <h3 class = "trunfo-main">
      <%= t :property_list_title%>
    </h2>
    <table class = "table table-sm table-properties" id="properties_table">
      <tbody>
        <%@properties.each do |property|%>
          <!-- Set Active class if current property -->
          <%cust_class = (property_selected? &&
            is_current_property?(property)) ?
            "table-active": ""%>	
          <!-- Show picture -->
        	<tr class="<%=cust_class%>">
            <!-- Show FontAwesome pic for now -->
            <td class="align-middle">
              <i class="fas fa-home fa-3x trunfo-main">
              </i>
            </td> 

            <!-- Description -->
            <td class = "align-middle"> 
              <h5><%=property.description%></h5>
            </td>  
            <!-- Address -->
            <td class = "align-middle ">
            	<address>
          	    <%=property.address%><br>
          	      <%= property.address2 if property.address2
          		    %>
          		    <%=property.city%><br>
          		    <%=property.state%> <%=property.zip%><br>
          	    
              </address>
            </td>
            <!-- Edit Property Link -->
            <td class = "align-middle">
              <%= link_with_icon(
                  edit_property_path(id: property.id ),
                  "edit",
                  "edit_property_link",
                  (I18n.t :property_edit_title),
                  "",
                  false)%>
            </td>
            <!-- Delete Property Link -->
            <td class = "align-middle">
              <%=link_with_icon(
                property_path(property),
                "delete",
                "delete_property_link",
                (I18n.t :tooltip_delete_property),
                (I18n.t :property_del_confirm),
                true)%>

            </td>
            <!-- Manage Property Link -->
            <td class = "align-middle">
              <%if property_selected? && 
                   is_current_property?(property)%>	
                <i class="far fa-folder-open fa-2x trunfo-main" aria-hidden="true" data-html="true" data-toggle="tooltip" title="<%= t :tooltip_managing_property%>">
                </i> 
              <%else%>
                <%= link_with_icon(
                select_property_path(id: property.id),
                "manage",
                "manage_property_link",
                (I18n.t :tooltip_select_to_manage),
                "",
                true) %>
                  
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>  
  </div>
</div>

app/views/properties/edit.html.erb
<div class = "row">
  <div class = "col-8 offset-2">
  	<div class = "card">
  	  <div class = "card-header login_header">
  	    <h2><%= t :property_new_title%></h2>
  	  </div>	
      <!-- Show errors if any -->
  	  <div class = "card-body px-3">
        <%= render :partial => "shared/error_handling",
        :locals => {:the_object => @property,
                    :objectname => 'Property'} %>
        <%= form_for @property,:html=>{:multipart => true} do |f|%>            
        <!-- Render the form -->
  	    <%= render :partial => 'form',
        :locals => {:f => f}%>
      </div>
    </div>
    <br>
    <!-- Save button -->  
    <div class="col-4" style="padding-left: 0px">
      <%= f.submit (t :save_property_button),
          class: 'btn btn-trunfo btn-block' %>
    </div>
    <% end %>
  </div>
</div>    

app/views/properties/index.html.erb
<div id="properties">
   <!-- Render the property list or message -->
  <%if @properties.size > 0 %>
    <%=render partial: 'property_list'%>
  <%else%>
    <%=render partial: 'no_properties'%>
  <%end%>
</div>
<br>
<!-- Button to Add Property -->
<div class = "row">
  <div class = "col-6 col-md-3 col-lg-2 col-xl-2">
    <%= link_to (I18n.t :add_property_button), new_property_path,
    data: {turbolinks: false}, class: "btn btn-block btn-trunfo"%>
  </div>
</div>

app/views/properties/new.html.erb
<div class = "row">
  <div class = "col-12 col-md-8 col-lg-8 col-sm-8 offset-lg-2 offset-sm-2 offset-md-2">
  	<div class = "card">
  	  <div class = "card-header login_header">
  	    <h2><%= t :property_new_title%></h2>
  	  </div>	
      <!-- Show errors if any -->
  	  <div class = "card-body px-3">
        <%= render :partial => "shared/error_handling",
        :locals => {:the_object => @property,
                    :objectname => 'Property'} %>
        <!-- Render the form -->
        <%= form_for @property,:html=>{:multipart => true} do |f|%>
  	      <%= render :partial => 'form',
          :locals => {:f => f}%>
      </div>
    </div>
    <br>
    <!-- Save button -->  
    <div class="col-6 col-md-4 col-lg-3 col-xl-3"
    style="padding-left: 0px">
      <%= f.submit (t :save_property_button),
          class: 'btn btn-trunfo btn-block' %>
    </div>
    <% end %>
  </div>
</div>    

app/views/properties/show.html.erb
<h1>show.html.erb</h1>

app/views/shared/_error_handling.html.erb
<% if the_object.errors.any? %>
  <div id="error_explanation"
    class = "card border-danger mb-3">
    <div class = "card-header text-danger">
      <%= I18n.t("error_handling.messages.not_saved",
      count: the_object.errors.count, resource: objectname)%>
      <div class = "card-body text-danger">
        <ul>
          <% the_object.errors.messages.values.each do |message| %>
            <%message.each do |m|%>
            <li> 
              <%= m%>
            </li>
            <%end%>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_login_status_links.html.erb
<ul class="navbar-nav ml-auto">
  <li class = "nav-item">
    <%=link_to (t :about) , about_path, class: 'nav-link'%>
  </li>
  <!-- If User is Logged In, we show the Sign Out button -->
  <% if signed_in? %>
    <% if property_selected? %>
      <li class = "navbar-text" 
      style = "padding-right: 10px; padding-left: 10px">
        <%=current_property.description%>
      </li>
    <%else%>
      <li class="navbar-text" 
        style = "padding-right: 10px; padding-left: 10px">
        No property selected
      </li>
    <%end%>

    <%= link_to "Log Out", destroy_user_session_path,
      method: :delete,
      class: 'btn btn-trunfo navbar-btn' %>
  <%end%>

</ul>

app/views/shared/_menu_user.html.erb
<!-- FRANCHISE USER -->
<ul class="navbar-nav mr-auto">
  <li class = "nav-item">
    <%=link_to (t :account) , edit_user_registration_path, class: 'nav-link'%>
  </li>  
  <!-- PROPERTIES -->
  <li class ="nav-item">
    <%=link_to (t :properties) ,  properties_path,class: 'nav-link'%>
  </li>  

  <!-- ROOMS -->
  <li class="nav-item">
  
    <%=link_to (t :rooms) ,  '#',class: 'nav-link'%>
  </li> 

    <!-- ITEMS -->
  <li class="nav-item">
    <%=link_to (t :items) , '#',class: 'nav-link'%>
  </li>  

  
</ul>

app/views/shared/_menubar.html.erb
<div class="navbar-collapse collapse " id="main-nav-collapse">
  <!-- If User is Logged In -->
  <% if signed_in? %> 
      <%=render "shared/menu_user" %>
  <%end%>

  <!--SHOW THE SIGN OUT OR LOGIN LINKAT THE END -->
  <%= render "shared/login_status_links" %>  
  
</div>